on:
  push: 
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader

      - run: |
          cp .env.example .env
          sed -i 's/ZOHO_DOMAIN=/ZOHO_DOMAIN="${{ secrets.ZOHO_DOMAIN }}"/g' .env
          sed -i 's/ZOHO_CLIENT_ID=/ZOHO_CLIENT_ID=${{ secrets.ZOHO_CLIENT_ID }}/g' .env
          sed -i 's/ZOHO_CLIENT_SECRET=/ZOHO_CLIENT_SECRET=${{ secrets.ZOHO_CLIENT_SECRET }}/g' .env
          sed -i 's/ZOHO_REDIRECT_URI=/ZOHO_REDIRECT_URI=${{ secrets.ZOHO_REDIRECT_URI }}/g' .env
          sed -i 's/ZOHO_SCOPE=/ZOHO_SCOPE=${{ secrets.ZOHO_SCOPE }}/g' .env

      - run: php artisan key:generate

      - uses: actions/setup-node@v2
        with:
          node-version: '18'

      - run: |
          npm install
          npm run build
          rm -rf node_modules

      - uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: './'
          target: '/var/www/zoho'

      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
              cd /var/www/zoho
              chown -R www-data:www-data .
              find . -type d -exec chmod 755 {} \;
              chmod -R 775 storage bootstrap/cache
              find . -type f -exec chmod 644 {} \;